kind: Deployment
apiVersion: apps/v1
metadata:
  name: weather-forecast-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-forecast-microservice
  template:
    metadata:
      labels:
        app: weather-forecast-microservice
    spec:
      containers:
        - name: weather-forecast-microservice
          image: weather-forecast-microservice-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: weather-forecast-microservice
spec:
  type: LoadBalancer
  ports:
    - name: weather-forecast-microservice
      port: 6000
      targetPort: 80
  selector:
    app: weather-forecast-microservice
  